Repository WildCodeSchool/2023-09-PHP-LYON-P3-nom-nom-nom, pull requests merged in 2023-12, with the labels that each got.

#1 created database recipe
  migrations/Version20231211161605.php
  src/Entity/Recipe.php
  src/Repository/RecipeRepository.php
Labels: Needs pair review

#3 S01 us05show steps
  migrations/Version20231213103320.php
  src/Controller/RecipeController.php
  src/Controller/StepController.php
  src/Entity/Recipe.php
  src/Entity/Step.php
  src/Form/StepType.php
  src/Repository/StepRepository.php
  templates/recipe/recipe_step.html.twig
  templates/step/_delete_form.html.twig
  templates/step/_form.html.twig
  templates/step/edit.html.twig
  templates/step/new.html.twig
  templates/step/show.html.twig
Labels: Changes done

#4 S01 us03 watch recipe
  assets/images/cassoulet_1.jpg
  assets/images/cassoulet_2.jpg
  assets/images/cassoulet_3.jpg
  migrations/Version20231213144758.php
  src/DataFixtures/RecipeFixture.php
  src/Entity/Recipe.php
  src/Form/RecipeType.php
  templates/recipe/_form.html.twig
  templates/recipe/new.html.twig
  templates/recipe/show.html.twig
  webpack.config.js
Labels: Needs pair review

#6 update the bdd
  migrations/Version20231214095648.php
  src/DataFixtures/RecipeFixture.php
Labels: Needs pair review

#7 S1 us09 navbar
  assets/images/biglogo.png
  assets/styles/app.css
  assets/styles/app.scss
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Needs pair review

#9 add an input on recipe type for add a picture then delete the return …
  src/Controller/RecipeController.php
  src/Form/RecipeType.php
  templates/recipe/show.html.twig
Labels: Changes requested

#10 SCSS done for home page and view recipe
  assets/bootstrap.js
  assets/images/stock-chicken.png
  assets/styles/app.scss
  src/DataFixtures/RecipeFixture.php
  templates/home/index.html.twig
  templates/recipe/_delete_form.html.twig
  templates/recipe/show.html.twig
Labels: Needs pair review

#13 S02 us02constraintandform
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20231217164411.php
  src/Controller/StepController.php
  src/DataFixtures/RecipeFixture.php
  src/DataFixtures/StepFixtures.php
  src/Entity/Recipe.php
  src/Entity/Step.php
  src/Form/RecipeType.php
  src/Form/StepType.php
  symfony.lock
  templates/step/edit.html.twig
  templates/step/new.html.twig
  templates/step/show.html.twig
Labels: Needs pair review

#15 S02 us04form recipe app step
  assets/controllers/form-collection_controller.js
  assets/images/nomnomlogo.png
  assets/index.js
  assets/styles/app.scss
  config/packages/twig.yaml
  src/Controller/RecipeController.php
  src/Entity/Step.php
  src/Form/RecipeType.php
  src/Form/StepType.php
  templates/home/index.html.twig
  templates/recipe/_form.html.twig
  templates/recipe/edit.html.twig
  templates/recipe/index.html.twig
  templates/recipe/new.html.twig
  templates/recipe/recipe_step.html.twig
Labels: Changes done

#16 view page recipe-steps ok
  assets/images/background-pages.png
  assets/styles/app.scss
  templates/recipe/recipe_step.html.twig
Labels: Needs pair review

#17 S02 us05 navba mobile
  assets/app.js
  assets/images/menu_bento.png
  assets/styles/app.scss
  templates/base.html.twig
  templates/components/_navbar.html.twig
Labels: Changes requested, Changes done

#18 S02 us07/home desktop
  assets/images/background-home.png
  assets/images/background-pages.png
  assets/images/background.png
  assets/images/dessert.png
  assets/images/entree.png
  assets/images/plat.png
  assets/styles/app.scss
  templates/home/index.html.twig
Labels: Changes done

#21 S03 us07edit recipe
  assets/controllers/form-collection_controller.js
  assets/index.js
  assets/styles/app.scss
  src/Controller/RecipeController.php
  src/Entity/Recipe.php
  src/Form/RecipeType.php
  templates/recipe/edit.html.twig
  templates/recipe/recipe_step.html.twig
  templates/recipe/show.html.twig
Labels: Needs pair review
