Repository WildCodeSchool/2023-09-PHP-LYON-P3-nom-nom-nom, pull requests merged in 2024-01, with the labels that each got.

#22 S03 us09 crud user form connexion
  assets/images/Windows_Repair_Toolbox.exe.lnk
  assets/images/backgound-desktop-login.png
  assets/images/background_login.png
  assets/images/fond-desktop.png
  assets/images/fond_login.png
  assets/images/logo-blanc.png
  assets/images/logo_nom_white.png
  assets/images/logo_red_2000.png
  assets/images/logo_red_500.png
  assets/images/logo_red_900.png
  assets/images/logo_white_2000.png
  assets/images/logo_white_500.png
  assets/images/logo_white_900.png
  assets/images/pancake.jpg
  assets/images/photo_login.jpg
  assets/images/photo_register.jpg
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/mailer.yaml
  config/packages/security.yaml
  config/routes.yaml
  config/services.yaml
  migrations/Version20231230164721.php
  migrations/Version20231230190445.php
  src/Controller/LoginController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Recipe.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/UserRepository.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/base.html.twig
  templates/components/_navbar.html.twig
  templates/login/index.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/index.html.twig
  templates/registration/register.html.twig
Labels: Changes done

#23 S03 us08deletereceipe
  src/Controller/RecipeController.php
  src/Entity/Step.php
  src/Repository/StepRepository.php
  templates/base.html.twig
  templates/recipe/_delete_form.html.twig
  templates/recipe/_form.html.twig
  templates/recipe/edit.html.twig
  templates/recipe/recipe_step.html.twig
  templates/recipe/show.html.twig
Labels: Needs pair review

#24 S01 us04/ingredients
  assets/images/cacahuètes.jpeg
  assets/images/carotte.png
  assets/images/echinedeporc.jpeg
  assets/images/escalopedepoulet.jpeg
  assets/images/filetdeporc.jpeg
  assets/images/haricotblanc.jpeg
  assets/images/huileolive.jpeg
  assets/images/laitue.jpeg
  assets/images/oignon.png
  assets/images/saucissedetoulouse.png
  assets/images/thym.jpeg
  assets/images/tomate.png
  assets/styles/app.scss
  composer.json
  composer.lock
  migrations/Version20240103135023.php
  migrations/Version20240103142401.php
  src/Controller/IngredientController.php
  src/Controller/RecipeController.php
  src/DataFixtures/IngredientFixtures.php
  src/DataFixtures/RecipeFixture.php
  src/DataFixtures/RecipeIngredientFixtures.php
  src/DataFixtures/StepFixtures.php
  src/Entity/Ingredient.php
  src/Entity/Recipe.php
  src/Entity/RecipeIngredient.php
  src/Form/IngredientType.php
  src/Repository/IngredientRepository.php
  src/Repository/RecipeIngredientRepository.php
  templates/ingredient/_delete_form.html.twig
  templates/ingredient/_form.html.twig
  templates/ingredient/edit.html.twig
  templates/ingredient/index.html.twig
  templates/ingredient/new.html.twig
  templates/recipe/recipe_ingredients.html.twig
Labels: Changes requested

#26 S03 us12 secure pathes
  config/packages/security.yaml
  migrations/Version20240104150558.php
  src/Controller/RecipeController.php
  src/Entity/Recipe.php
  src/Entity/User.php
  templates/components/_messages.html.twig
  templates/recipe/index.html.twig
  templates/recipe/recipe_ingredients.html.twig
  templates/recipe/recipe_step.html.twig
  templates/recipe/show.html.twig
  templates/step/_delete_form.html.twig
Labels: Needs pair review

#27 S03 us16/majnewrecipe
  assets/controllers/form-collection_controller.js
  src/Controller/RecipeController.php
  src/Form/RecipeIngredientType.php
  src/Form/RecipeType.php
  templates/recipe/_delete_form.html.twig
  templates/recipe/_form.html.twig
  templates/recipe/edit.html.twig
  templates/recipe/recipe_step.html.twig
Labels: Needs pair review

#28 debug view recipe according on desktop and mobile
  assets/images/background-home.png
  assets/images/background-pages.png
  assets/styles/app.scss
  templates/home/index.html.twig
  templates/recipe/show.html.twig
Labels: Changes requested

#29 S03 us16search in form
  assets/controllers.json
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig_component.yaml
  config/routes/ux_autocomplete.yaml
  config/routes/ux_live_component.yaml
  package.json
  src/Controller/RecipeController.php
  src/Form/RecipeIngredientType.php
  src/Repository/RecipeRepository.php
  src/Twig/Components/RecipeAllSearch.php
  symfony.lock
  templates/components/RecipeAllSearch.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Needs pair review

#30 S03 us04 debug page etape
  assets/controllers/form-collection_controller.js
  assets/styles/app.scss
  src/Form/IngredientType.php
  src/Form/RecipeType.php
  src/Form/StepType.php
  templates/recipe/_form.html.twig
  templates/recipe/new.html.twig
  templates/recipe/recipe_step.html.twig
Labels: Needs pair review

#32 S03 us17 sidebar recipe page
  assets/app.js
  assets/styles/app.scss
  src/Form/RecipeIngredientType.php
  templates/components/RecipeAllSearch.html.twig
  templates/components/_sidebarRecipe.html.twig
  templates/recipe/recipe_ingredients.html.twig
  templates/recipe/recipe_step.html.twig
  templates/recipe/show.html.twig
Labels: Needs pair review

#34 S03 us18 recipespage
  assets/images/baguette_pain.jpeg
  assets/images/nuoc-mam.jpeg
  assets/images/poulet_haricot.jpeg
  assets/images/sandwich.jpeg
  assets/styles/app.scss
  src/Controller/HomeController.php
  src/Controller/RecipeController.php
  src/DataFixtures/IngredientFixtures.php
  src/DataFixtures/RecipeFixture.php
  src/DataFixtures/RecipeIngredientFixtures.php
  src/DataFixtures/StepFixtures.php
  src/Entity/Ingredient.php
  src/Entity/Recipe.php
  src/Entity/Step.php
  src/Repository/RecipeRepository.php
  templates/components/_sidebarRecipe.html.twig
  templates/home/index.html.twig
  templates/recipe/index.html.twig
  templates/recipe/recipe_step.html.twig
Labels: Changes done

#31 S03 us06 debug login navbar
  assets/app.js
  assets/styles/app.scss
  config/packages/security.yaml
  src/Controller/IngredientController.php
  src/Controller/RecipeController.php
  src/Controller/StepController.php
  src/Service/AccessControl.php
  templates/components/_navbar.html.twig
  templates/login/index.html.twig
  templates/recipe/_delete_form.html.twig
  templates/recipe/show.html.twig
Labels: Changes requested, Changes done

#35 S03 us19category
  assets/styles/app.scss
  migrations/Version20240109153404.php
  src/Controller/CategoryController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/RecipeFixture.php
  src/DataFixtures/StepFixtures.php
  src/Entity/Category.php
  src/Entity/Recipe.php
  src/Form/CategoryType.php
  src/Form/RecipeType.php
  src/Repository/CategoryRepository.php
  templates/recipe/_form.html.twig
Labels: Changes done

#37 S03 us13 user page
  assets/images/user.png
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  src/Controller/RecipeController.php
  src/Controller/SecurityController.php
  symfony.lock
  templates/baseEmail.html.twig
  templates/components/_navbar.html.twig
  templates/emails/newRecipeEmail.html.twig
  templates/security/profile.html.twig
Labels: Changes requested, Changes done

#38 S03 us21recipes page with category
  assets/styles/app.scss
  src/Controller/RecipeController.php
  src/Repository/CategoryRepository.php
  src/Repository/IngredientRepository.php
  src/Repository/RecipeIngredientRepository.php
  src/Repository/RecipeRepository.php
  src/Repository/StepRepository.php
  templates/recipe/index.html.twig
Labels: Needs pair review

#39 change the parameter in qerySelectorAll for the method changeIconColo…
  assets/app.js
Labels: Needs pair review

#40 S03 us19 debug edit ingredient
  assets/app.js
  assets/controllers/form-collection_controller.js
  assets/styles/app.scss
  migrations/Version20240110160548.php
  migrations/Version20240111095423.php
  src/Controller/RecipeController.php
  src/Entity/RecipeIngredient.php
  src/Entity/Step.php
  src/Form/RecipeType.php
  src/Service/DeleteButtonService.php
  src/Service/UpdateNumberService.php
  templates/home/index.html.twig
  templates/recipe/_form.html.twig
  templates/recipe/edit.html.twig
  templates/recipe/new.html.twig
Labels: Needs pair review

#44 S03 us23password forget
  assets/styles/app.scss
  config/packages/reset_password.yaml
  migrations/Version20240111123612.php
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  templates/login/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: Needs pair review, Changes done

#45 S04 us01favorite recipe
  assets/app.js
  assets/styles/app.scss
  migrations/Version20240113205348.php
  package.json
  src/Controller/RecipeController.php
  src/Controller/SecurityController.php
  src/Entity/Recipe.php
  src/Entity/User.php
  src/Repository/RecipeRepository.php
  src/Repository/UserRepository.php
  src/Twig/Components/Favoritelist.php
  templates/components/Favoritelist.html.twig
  templates/components/_navbar.html.twig
  templates/components/_sidebarRecipe.html.twig
  templates/recipe/show.html.twig
  templates/security/profile.html.twig
  templates/security/profile_favorite.html.twig
  yarn.lock
Labels: Changes requested

#46 change request to search recipe only nameRecipe
  src/Repository/RecipeRepository.php
Labels: Changes done

#48 S04 us08 debug connexion user
  assets/app.js
  migrations/Version20240113205348.php
  src/Controller/LoginController.php
  templates/home/index.html.twig
Labels: Needs pair review

#51 S04 us07 debug vue recette
  assets/styles/app.scss
  templates/recipe/recipe_ingredients.html.twig
  templates/recipe/show.html.twig
Labels: Needs pair review

#55 slug added on searchbar
  assets/app.js
  templates/components/RecipeAllSearch.html.twig
  templates/home/index.html.twig
Labels: Needs pair review

#56 S04 us12comment recipe
  assets/styles/app.scss
  migrations/Version20240116150345.php
  src/Controller/CommentController.php
  src/Controller/RecipeController.php
  src/Controller/RecipeIngredientController.php
  src/Controller/RecipeStepController.php
  src/Entity/Comment.php
  src/Entity/Recipe.php
  src/Entity/User.php
  src/Form/CommentType.php
  src/Repository/CommentRepository.php
  src/Traits/ImageUploadTrait.php
  templates/comment/_delete_form.html.twig
  templates/comment/edit.html.twig
  templates/comment/index.html.twig
  templates/comment/show.html.twig
  templates/recipe/_form.html.twig
  templates/recipe/show.html.twig
  templates/security/profile_favorite.html.twig
Labels: Changes done

#57 S04 us13 test
  composer.json
  composer.lock
  config/packages/security.yaml
  tests/Controller/RecipeControllerTest.php
  tests/Unit/RecipeTest.php
Labels: Needs pair review

#58 S04 us17image
  build/images/7bef29c4-b3d4-4d09-9b7a-a83df0f4a6af-65afdd5bd4f89688113161.jpg
  config/services.yaml
  src/Controller/CategoryController.php
  src/Controller/HomeController.php
  src/Controller/RecipeController.php
  src/Controller/RecipeIngredientController.php
  src/Controller/RecipeStepController.php
  src/Service/ImageService.php
  templates/category/show.html.twig
  templates/home/index.html.twig
  templates/recipe/index.html.twig
  templates/recipe/recipe_ingredients.html.twig
  templates/recipe/recipe_step.html.twig
  templates/recipe/show.html.twig
Labels: Changes requested

#59 change all path for the picture, now we can see picture only which ar…
  src/Controller/CategoryController.php
  src/Controller/HomeController.php
  src/Controller/RecipeController.php
  src/Controller/RecipeIngredientController.php
  src/Controller/RecipeStepController.php
  src/Service/ImageService.php
  templates/category/show.html.twig
  templates/components/RecipeAllSearch.html.twig
  templates/home/index.html.twig
  templates/recipe/index.html.twig
  templates/recipe/recipe_ingredients.html.twig
  templates/recipe/recipe_step.html.twig
  templates/recipe/show.html.twig
Labels: Needs pair review

#61 S04 us14 admin page
  assets/images/camembert.png
  assets/images/flan.png
  assets/images/oeuf.png
  assets/images/soupe.png
  assets/images/tartare-saumon.png
  build/images/7bef29c4-b3d4-4d09-9b7a-a83df0f4a6af-65afdd5bd4f89688113161.jpg
  composer.json
  composer.lock
  config/bundles.php
  config/packages/uid.yaml
  config/service_test.yaml
  config/services.yaml
  src/Controller/Admin/CategoryCrudController.php
  src/Controller/Admin/CommentCrudController.php
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/IngredientCrudController.php
  src/Controller/Admin/RecipeCrudController.php
  src/Controller/Admin/Trait/ReadOnlyTrait.php
  src/Controller/Admin/UserCrudController.php
  src/Controller/CategoryController.php
  src/Controller/RecipeController.php
  src/Controller/StepController.php
  src/DataFixtures/RecipeFixture.php
  src/Entity/Comment.php
  src/Entity/Recipe.php
  src/Entity/RecipeIngredient.php
  src/Entity/Step.php
  src/Entity/User.php
  src/Form/IngredientType.php
  symfony.lock
  templates/components/_navbar.html.twig
Labels: Needs pair review

#63 debug some things
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/StepCrudController.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/base.html.twig
  templates/components/_navbar.html.twig
Labels: Needs pair review

#65 S04 debug 02
  assets/images/00228-3492288631.png
  assets/styles/app.scss
  src/Entity/Comment.php
  src/Form/CommentType.php
  src/Form/RecipeType.php
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/category/show.html.twig
  templates/home/index.html.twig
  templates/recipe/index.html.twig
  templates/recipe/show.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/profile_favorite.html.twig
  templates/security/profile_my_recipes.html.twig
Labels: Needs pair review

#67 S04 debug test stars
  assets/styles/app.scss
  src/Form/CommentType.php
  templates/recipe/show.html.twig
Labels: Changes done

#68 S04 debug03
  templates/recipe/index.html.twig
Labels: Changes done

#70 finish a lot of debug in registration, recipe view, admin
  assets/app.js
  assets/styles/app.scss
  src/Controller/Admin/DashboardController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/components/_sidebarRecipe.html.twig
  templates/recipe/show.html.twig
  templates/registration/register.html.twig
Labels: Needs pair review

#71 S04 debuglogin
  src/Controller/LoginController.php
Labels: Changes done

#73 changes on SCSS ,routes' names
  assets/images/fond_login.png
  assets/styles/app.scss
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  templates/security/profile.html.twig
  templates/security/profile_edit.html.twig
Labels: Changes done

#74 S04 debug flash messages
  assets/styles/app.scss
  src/Controller/LoginController.php
  templates/base.html.twig
  templates/components/_messages.html.twig
  templates/home/index.html.twig
Labels: Needs pair review, Changes done

#76 S05 one day at summer camp
  config/packages/web_profiler.yaml
  src/Controller/LoginController.php
  src/Controller/RecipeController.php
  templates/recipe/show.html.twig
Labels: Needs pair review
